# 14. Dataframes with the `pandas` module

**Dataframe.** It is a mutable two-dimensional data structure with the axes labeled where

- each row represents a different observation
- each column represents a different variable

In `Python`, to define a dataframe, we first need to import the `pandas` module.

In [1]:
import pandas as pd

We can create dataframes from a dictionary, a list of lists, a list of dictionaries, etc.

In [2]:
# Dataframes from a dictionary

data = {"x": [1, 2, 3, 4, 5], "y": [2, 4, 6, 8, 10]}
df1 = pd.DataFrame(data = data)
print(df1)

   x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [3]:
# Dataframe from a list of lists

df2 = pd.DataFrame(data = [[1, 2], [2, 4], [3, 6], [4, 8], [5, 10]],
                   columns = ["x", "y"])
print(df2)

   x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [4]:
# We can modify the name of the rows with the `index` parameter.

df3 = pd.DataFrame(data = data, index = ["obs1", "obs2", "obs3", "obs4", "obs5"])
print(df3)

      x   y
obs1  1   2
obs2  2   4
obs3  3   6
obs4  4   8
obs5  5  10

In [5]:
# Dataframe from a list of dictionaries

data = [{"x": 1, "y": 2},
        {"x": 2, "y": 4},
        {"x": 3, "y": 6},
        {"x": 4, "y": 8},
        {"x": 5, "y": 10}]
df4 = pd.DataFrame(data = data)
print(df4)

   x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [6]:
# We can create a dataframe using the `zip()` function.

x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

data = list(zip(x, y))
print("Data:\n")
print(data)

print("-----------------------------------------")

print("Dataframe:\n")
df5 = pd.DataFrame(data, columns = ["x", "y"])
print(df5)

Data:

[(1, 2), (2, 4), (3, 6), (4, 8), (5, 10)]
-----------------------------------------
Dataframe:

   x   y
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

## 14.1. File upload

### 14.1.1. `txt` files

In [7]:
%cd C:/Users/RJKANG/Desktop/quant/Statistical Learning/Introduction to Statistical Learning/

C:\Users\RJKANG\Desktop\quant\Statistical Learning\Introduction to Statistical Learning

In [8]:
# The `open()` function opens the indicated file and allows us to access it.

f = open("first_read.txt")

# We use the `.read()` method to read the content of the output provided by the 
# `open()` function to which we have called `f`

print(f.read())

# * When we have finished working with the `f` file, we must close it. 
# This process is carried out with the `.close()` method

f.close()

"Hello world from Python!"

In [9]:
# Another way to open the file and save it in the `f` variable would be:

with open("first_read.txt") as f:
    print(f.read())

# With this new syntax it is no longer necessary to use the `.close()` method to close the `f` file. 
# The `with` command ensures that the preceding `file` object, `f`, 
# will be automatically closed after exiting the code block.

"Hello world from Python!"

In [10]:
# Given a `txt` file opened with the `open()` function, it is not necessary to read the entire file. 
# If we were only interested in reading a part, we could indicate it by parameter to the `.read()` method

f = open("first_read.txt") 
print(f.read(7))
f.close()

"Hello

In [11]:
# The `.readline()` method causes the file `f` to be read line by line.

with open("first_read_multiline.txt") as f:
    print(f.readline())
    print(f.readline())
    print(f.readline())

"Hello world

from

Python!"

In [12]:
# We can create and write a `txt` file from this same notebook.

f = open("first_write.txt", mode = "w")
f.write("This is the first txt file we wrote\nand we are doing it from Jupyter notebook!")
f.close()

In [13]:
with open("first_write.txt") as f:
    print(f.read())

This is the first txt file we wrote
and we are doing it from Jupyter notebook!

In [14]:
# Since there is more than one line, we can also read all of them with a loop:

with open("first_write.txt") as f:
    for line in f:
        print(line)

This is the first txt file we wrote

and we are doing it from Jupyter notebook!

In [15]:
# If we want to create an empty `txt`, we indicate `mode = "x"`

f = open("first_empty.txt", mode = "x")
f.close()

In [16]:
# Just like we can create and write a `txt` file from scratch, we can modify an existing `txt` file.

f = open("first_write.txt", mode = "a")
f.write("\nY esta última línea se ha añadido posteriormente.")
f.close()

In [17]:
# Deleting files

import os

In [18]:
# To delete a file we will use the `.remove()` method

os.remove("first_empty.txt")

In [19]:
f = open("first_empty.txt", mode = "x")
f.close()

In [20]:
if os.path.exists("first_empty.txt"):
    os.remove("first_empty.txt")
else:
    print("El archivo que se quiere eliminar no existe")

In [21]:
if os.path.exists("first_empty.txt"):
    os.remove("first_empty.txt")
else:
    print("El archivo que se quiere eliminar no existe")

El archivo que se quiere eliminar no existe

### 14.1.2. `csv` files

In [22]:
import csv

In [23]:
# To read a `csv` we use the `.reader()` method of the `csv` module.

# With the `open()` function we have accessed the file, which we have identified by `f`.
with open("csv_example.csv", "r") as f:
    # Next, we have used the `.reader()` method to read the file `f`. 
    # This method has returned us the iterable `reader`, of which we 
    # have shown all its rows iterating with a `for` loop.
    reader = csv.reader(f)
    for row in reader:
        print(row)

['id', 'Name', 'City', 'Age']
['1234', 'Arturo', 'Madrid', '22']
['2345', 'Beatriz', 'Barcelona', '25']
['3456', 'Carlos', 'Sevilla', '18']
['4567', 'Dolores', 'Cuenca', '34']

In [24]:
# The `.reader()` method allows us to configure said separator with the `delimiter` parameter

with open("csv_delimiter_example.csv", "r") as f:
    reader = csv.reader(f, delimiter = "|")
    for row in reader:
        print(row)

['id', 'Name', 'City', 'Age']
['1234', 'Arturo', 'Madrid', '22']
['2345', 'Beatriz', 'Barcelona', '25']
['3456', 'Carlos', 'Sevilla', '18']
['4567', 'Dolores', 'Cuenca', '34']

In [25]:
# To remove extra whitespace, the `.reader()` method brings the `skipinitialspace` parameter. 
# If we set it to `True`, the extra spaces will disappear.

# skipinitialspace = False (default)
with open("csv_spaces_example.csv", "r") as f:
    reader = csv.reader(f, skipinitialspace = False)
    for row in reader:
        print(row)

['id', ' Name', ' City', ' Age']
['1234', ' Arturo', ' Madrid', ' 22']
['2345', ' Beatriz', ' Barcelona', ' 25']
['3456', ' Carlos', ' Sevilla', ' 18']
['4567', ' Dolores', ' Cuenca', ' 34']

In [26]:
# If instead we want quotes, we have the `quoting` parameter, which admits different values:

with open("csv_quotation_example.csv", "r") as f:
    reader = csv.reader(f, quoting = csv.QUOTE_NONNUMERIC)
    for row in reader:
        print(row)

['id', 'Name', 'City', 'Age']
[1234.0, 'Arturo', 'Madrid', 22.0]
[2345.0, 'Beatriz', 'Barcelona', 25.0]
[3456.0, 'Carlos', 'Sevilla', 18.0]
[4567.0, 'Dolores', 'Cuenca', 34.0]

In [27]:
with open("csv_quotation_example.csv", "r") as f:
    reader = csv.reader(f, quoting = csv.QUOTE_ALL)
    for row in reader:
        print(row)

['id', 'Name', 'City', 'Age']
['1234', 'Arturo', 'Madrid', '22']
['2345', 'Beatriz', 'Barcelona', '25']
['3456', 'Carlos', 'Sevilla', '18']
['4567', 'Dolores', 'Cuenca', '34']

In [28]:
# Dialects

# We give the `.register_dialect()` method a name in `string` format and then set the `delimiter`,
# `skipinitialspace` and `quoting` parameters.

# Next, to the `.reader()` method we give the name of the dialect, `my_dialect`, to the `dialect` 
# parameter and thus we read the file correctly.

# Once the custom dialect is created, we can use it as many times as we want to open and read `csv` 
# files with the same format, in this case, as `csv_dialect_example.csv`. 


csv.register_dialect("my_dialect",
                     delimiter = "|",
                     skipinitialspace = True,
                     quoting = csv.QUOTE_NONNUMERIC)

with open("csv_dialect_example.csv", "r") as f:
    reader = csv.reader(f, dialect = "my_dialect")
    for row in reader:
        print(row)

['id', 'Name', 'City', 'Age']
[1234.0, 'Arturo', 'Madrid', 22.0]
[2345.0, 'Beatriz', 'Barcelona', 25.0]
[3456.0, 'Carlos', 'Sevilla', 18.0]
[4567.0, 'Dolores', 'Cuenca', 34.0]

In [29]:
# Dictionaries and `csv`

# With the `.DictReader()` method of the `csv` module, we return an `OrderedDict` object, which is iterable.

with open("csv_example.csv", "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        print(row)

{'id': '1234', 'Name': 'Arturo', 'City': 'Madrid', 'Age': '22'}
{'id': '2345', 'Name': 'Beatriz', 'City': 'Barcelona', 'Age': '25'}
{'id': '3456', 'Name': 'Carlos', 'City': 'Sevilla', 'Age': '18'}
{'id': '4567', 'Name': 'Dolores', 'City': 'Cuenca', 'Age': '34'}

In [30]:
# # We could use the `dict()` function inside `print()` to display `OrderedDict` objects as dictionaries.

with open("csv_example.csv", "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        print(dict(row))

{'id': '1234', 'Name': 'Arturo', 'City': 'Madrid', 'Age': '22'}
{'id': '2345', 'Name': 'Beatriz', 'City': 'Barcelona', 'Age': '25'}
{'id': '3456', 'Name': 'Carlos', 'City': 'Sevilla', 'Age': '18'}
{'id': '4567', 'Name': 'Dolores', 'City': 'Cuenca', 'Age': '34'}

In [31]:
# To create and write a `csv` we use the `open()` function together with the `csv.writer()` method:

data = [["id", "Name", "City", "Age"], 
        [1234, "Arturo", "Madrid", 22], 
        [2345, "Beatriz", "Barcelona", 25],
        [3456, "Carlos", "Sevilla", 18], 
        [4567, "Dolores", "Cuenca", 34]]

with open("csv_write.csv", "w") as f:
    writer = csv.writer(f)
    for row in data:
        writer.writerow(row)

In [32]:
# We can do the same as the previous chunk of code without using a loop, using the .writerows() method.

with open("csv_write_writerows.csv", "w") as f:
    writer = csv.writer(f)
    writer.writerows(data)

In [33]:
# We can write a `csv` from a dictionary. To do this we will have to use the `.DictWriter()` method.

data = [{"id": 1234, "Name": "Arturo", "City": "Madrid", "Age": 22},
        {"id": 2345, "Name": "Beatriz", "City": "Barcelona", "Age": 25},
        {"id": 3456, "Name": "Carlos", "City": "Sevilla", "Age": 18},
        {"id": 4567, "Name": "Dolores", "City": "Cuenca", "Age": 34}]

# The header is the list of the keys of any of the data entries
header = list(data[0].keys())

with open("csv_write_dict.csv", "w") as f:
    writer = csv.DictWriter(f, fieldnames = header)

    writer.writeheader()
    for d in data:
        writer.writerow(d)

In [34]:
# We could have obtained the same result without using any loops, but using the `.writerows()` method

with open("csv_write_dict_writerows.csv", "w") as f:
    writer = csv.DictWriter(f, fieldnames = header)

    writer.writeheader()
    writer.writerows(data)

## 14.2. Dataframes from files

### 14.2.1. Dataframes from CSV files

We can save the information from a csv file to a dataframe using the `read_csv()` function.

The file can

- be saved in our working directory
- come from a url

**From url**: We are going to load the file that contains the frequency of appearance of the letters of the English alphabet. This file is called letter_frequency.csv comes from the following [url](https://people.sc.fsu.edu/~jburkardt/data/csv/letter_frequency.csv)

In [35]:
letters_freq_df = pd.read_csv("https://people.sc.fsu.edu/~jburkardt/data/csv/letter_frequency.csv")
letters_freq_df.columns = ["Letter", "Frequency", "Percentage"]
letters_freq_df

     Letter  Frequency  Percentage
0       "A"   24373121         8.1
1       "B"    4762938         1.6
2       "C"    8982417         3.0
3       "D"   10805580         3.6
4       "E"   37907119        12.6
5       "F"    7486889         2.5
6       "G"    5143059         1.7
7       "H"   18058207         6.0
8       "I"   21820970         7.3
9       "J"     474021         0.2
10      "K"    1720909         0.6
11      "L"   11730498         3.9
12      "M"    7391366         2.5
13      "N"   21402466         7.1
14      "O"   23215532         7.7
15      "P"    5719422         1.9
16      "Q"     297237         0.1
17      "R"   17897352         5.9
18      "S"   19059775         6.3
19      "T"   28691274         9.5
20      "U"    8022379         2.7
21      "V"    2835696         0.9
22      "W"    6505294         2.2
23      "X"     562732         0.2
24      "Y"    5910495         2.0
25      "Z"      93172         0.0

### 14.2.2. Dataframes from JSON files

We can save the information from a json file to a dataframe using the `.read_json()` method.

The file can

- be saved in our working directory
- come from a url

In [36]:
quiz_index = pd.read_json("json_index_example.json", 
                          orient = "index")
quiz_index.head()

    Producto  Precio  Cantidad
0  Bolígrafo    1.80         3
1      Lápiz    0.30         2
2    Libreta    5.20         1
3     Agenda    9.99         1
4  Rotulador    1.15         5

**The `orient` parameter**:

In the case of json files, it could be that they do not have the same configuration as our example, `json_index_example.json` whose orientation corresponds to `index`.

The `orient` parameter of the `.read_json()` method supports other options such as `columns` or `values`.

Let's see both cases with the files `json_columns_example.json` and `json_values_example.json`, respectively.

In [37]:
# Orientation with index
quiz_columns = pd.read_json("json_columns_example.json", 
                    orient = "columns")
quiz_columns.head()

    Producto  Precio  Cantidad
0  Bolígrafo    1.80         3
1      Lápiz    0.30         2
2    Libreta    5.20         1
3     Agenda    9.99         1
4  Rotulador    1.15         5

In [38]:
# Orientation with values
quiz_values = pd.read_json("json_values_example.json",
                           orient = "values")
quiz_values.head()

           0     1  2
0  Bolígrafo  1.80  3
1      Lápiz  0.30  2
2    Libreta  5.20  1
3     Agenda  9.99  1
4  Rotulador  1.15  5

**From url**: We are going to load the json file that comes from the following [url](https://api.exchangerate-api.com/v4/latest/USD)

In [39]:
from_url = pd.read_json("https://api.exchangerate-api.com/v4/latest/USD")
from_url.head()

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2024-03-04,1709510401,3.67
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2024-03-04,1709510401,73.18
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2024-03-04,1709510401,95.94
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2024-03-04,1709510401,403.96
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,USD,2024-03-04,1709510401,1.79

## 14.3. Dataframe methods

| Method            | Description                                   |
|-------------------|-----------------------------------------------|
| `.from_dict()`    | Creates a DataFrame from a dictionary        |
| `.shape`          | Returns the dimensions of the DataFrame      |
| `.info()`         | Provides a concise summary of the DataFrame's info |
| `.describe()`     | Generates descriptive statistics of the DataFrame |
| `.size`           | Returns the number of elements in the DataFrame |
| `.ndim`           | Returns the number of dimensions (axes) of the DataFrame |
| `[:]`             | Selects all rows of the DataFrame             |
| `.columns[]`      | Accesses the column labels of the DataFrame  |
| `.loc[]`          | Accesses a group of rows and columns by labels |
| `.iloc[]`         | Accesses group of rows and columns by integer position |
| `.head()`         | Returns the first n rows of the DataFrame    |
| `.tail()`         | Returns the last n rows of the DataFrame     |
| `.copy()`         | Creates a deep copy of the DataFrame         |
| `.rename()`       | Renames index/columns of the DataFrame       |
| `.insert()`       | Inserts new columns into the DataFrame       |
| `.drop()`         | Drops specified labels from rows or columns  |
| `.pop()`          | Removes and returns a column from the DataFrame |
| `.rank()`         | Computes numerical data ranks                |
| `.nunique()`      | Counts distinct observations over requested axis |
| `.duplicated()`   | Identifies duplicated rows in the DataFrame  |
| `.drop_duplicates()` | Removes duplicate rows from the DataFrame  |
| `.nsmallest()`    | Returns the first n smallest elements from the DataFrame |
| `.nlargest()`     | Returns the first n largest elements from the DataFrame |
| `.dtypes`         | Returns the data types of the DataFrame columns |
| `.isnull()`       | Detects missing values in the DataFrame      |
| `.notnull()`      | Detects non-missing values in the DataFrame  |
| `.fillna()`       | Fills missing values with specified method   |
| `.replace()`      | Replaces specified values in the DataFrame   |
| `.interpolate()`  | Interpolates missing values in the DataFrame |
| `.dropna()`       | Drops missing values from the DataFrame      |
| `.query()`        | Queries DataFrame with boolean expression    |
| `.iterrows()`     | Iterates over DataFrame rows as (index, Series) pairs |
| `.itertuples()`   | Iterates over DataFrame rows as namedtuples  |

In [40]:
# Create a dictionary with data
data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}

# Create a DataFrame from the dictionary with 'index' orientation
df = pd.DataFrame.from_dict(data, orient='index', columns=['X', 'Y', 'Z'])

print(df)

   X  Y  Z
A  1  2  3
B  4  5  6
C  7  8  9

In [41]:
# Create a sample DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}
df = pd.DataFrame(data)

# .shape - Returns the dimensions of the DataFrame
print("Shape of the DataFrame:", df.shape)

# .info() - Provides a concise summary of the DataFrame's info
print("\nInfo of the DataFrame:")
print(df.info())

# .describe() - Generates descriptive statistics of the DataFrame
print("\nDescriptive statistics of the DataFrame:")
print(df.describe())

# .size - Returns the number of elements in the DataFrame
print("\nSize of the DataFrame:", df.size)

# .ndim - Returns the number of dimensions (axes) of the DataFrame
print("\nNumber of dimensions of the DataFrame:", df.ndim)

Shape of the DataFrame: (3, 3)

Info of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes
None

Descriptive statistics of the DataFrame:
         A    B    C
count  3.0  3.0  3.0
mean   2.0  5.0  8.0
std    1.0  1.0  1.0
min    1.0  4.0  7.0
25%    1.5  4.5  7.5
50%    2.0  5.0  8.0
75%    2.5  5.5  8.5
max    3.0  6.0  9.0

Size of the DataFrame: 9

Number of dimensions of the DataFrame: 2

In [42]:
# Create a sample DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}
df = pd.DataFrame(data)

# [] - Selects all rows of the DataFrame
print("Selecting all rows of the DataFrame:")
print(df[:])

# .columns[] - Accesses the column labels of the DataFrame
print("\nAccessing column labels of the DataFrame:")
print(df.columns)

# .loc[] - Accesses a group of rows and columns by labels
print("\nAccessing rows and columns by labels:")
print(df.loc[0:1, ['A', 'B']])

# .iloc[] - Accesses group of rows and columns by integer position
print("\nAccessing rows and columns by integer position:")
print(df.iloc[0:2, 0:2])

# .head() - Returns the first n rows of the DataFrame
print("\nFirst 2 rows of the DataFrame:")
print(df.head(2))

# .tail() - Returns the last n rows of the DataFrame
print("\nLast 2 rows of the DataFrame:")
print(df.tail(2))

# .copy() - Creates a deep copy of the DataFrame
print("\nDeep copy of the DataFrame:")
df_copy = df.copy()
print(df_copy)

Selecting all rows of the DataFrame:
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

Accessing column labels of the DataFrame:
Index(['A', 'B', 'C'], dtype='object')

Accessing rows and columns by labels:
   A  B
0  1  4
1  2  5

Accessing rows and columns by integer position:
   A  B
0  1  4
1  2  5

First 2 rows of the DataFrame:
   A  B  C
0  1  4  7
1  2  5  8

Last 2 rows of the DataFrame:
   A  B  C
1  2  5  8
2  3  6  9

Deep copy of the DataFrame:
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [43]:
# Create a sample DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}
df = pd.DataFrame(data)

# .rename() - Renames index/columns of the DataFrame (with inplace argument)
print("Renaming columns of the DataFrame:")
df.rename(columns={'A': 'New_A', 'B': 'New_B', 'C': 'New_C'}, inplace=True)
print(df)

# .insert() - Inserts new columns into the DataFrame
print("\nInserting a new column 'D' into the DataFrame:")
df.insert(loc=3, column='D', value=[10, 11, 12])
print(df)

# .drop() - Drops specified labels from rows or columns
print("\nDropping column 'D' from the DataFrame:")
df.drop(columns=['D'], inplace=True)
print(df)

# .pop() - Removes and returns a column from the DataFrame
print("\nPop column 'New_C' from the DataFrame:")
column_c = df.pop('New_C')
print("Column C:", column_c)
print("DataFrame after popping column C:")
print(df)

# .rank() - Computes numerical data ranks (with ascending argument)
print("\nRanking values of column 'New_A' in ascending order:")
print(df['New_A'].rank(ascending=True))

# .nunique() - Counts distinct observations over requested axis
print("\nNumber of unique values in column 'New_B':", df['New_B'].nunique())

# .duplicated() - Identifies duplicated rows in the DataFrame
print("\nIdentifying duplicated rows:")
print(df.duplicated())

# .drop_duplicates() - Removes duplicate rows from the DataFrame
print("\nRemoving duplicate rows:")
print(df.drop_duplicates())

# .nsmallest() - Returns the first n smallest elements from the DataFrame
print("\nGetting the two smallest values from column 'New_A':")
print(df['New_A'].nsmallest(2))

# .nlargest() - Returns the first n largest elements from the DataFrame
print("\nGetting the two largest values from column 'New_A':")
print(df['New_A'].nlargest(2))

# .dtypes - Returns the data types of the DataFrame columns
print("\nData types of the DataFrame columns:")
print(df.dtypes)

Renaming columns of the DataFrame:
   New_A  New_B  New_C
0      1      4      7
1      2      5      8
2      3      6      9

Inserting a new column 'D' into the DataFrame:
   New_A  New_B  New_C   D
0      1      4      7  10
1      2      5      8  11
2      3      6      9  12

Dropping column 'D' from the DataFrame:
   New_A  New_B  New_C
0      1      4      7
1      2      5      8
2      3      6      9

Pop column 'New_C' from the DataFrame:
Column C: 0    7
1    8
2    9
Name: New_C, dtype: int64
DataFrame after popping column C:
   New_A  New_B
0      1      4
1      2      5
2      3      6

Ranking values of column 'New_A' in ascending order:
0    1.0
1    2.0
2    3.0
Name: New_A, dtype: float64

Number of unique values in column 'New_B': 3

Identifying duplicated rows:
0    False
1    False
2    False
dtype: bool

Removing duplicate rows:
   New_A  New_B
0      1      4
1      2      5
2      3      6

Getting the two smallest values from column 'New_A':
0    1
1    2
Name: New_A, dtype: int64

Getting the two largest values from column 'New_A':
2    3
1    2
Name: New_A, dtype: int64

Data types of the DataFrame columns:
New_A    int64
New_B    int64
dtype: object

In [44]:
import numpy as np

# Create a sample DataFrame with missing values
data = {'A': [1, np.nan, 3, 4, 5],
        'B': [np.nan, 2, np.nan, 4, 5],
        'C': [1, 2, 3, 4, 5]}
df = pd.DataFrame(data)

# .isnull() - Detects missing values in the DataFrame
print("Checking for missing values in the DataFrame:")
print(df.isnull())

# .notnull() - Detects non-missing values in the DataFrame
print("\nChecking for non-missing values in the DataFrame:")
print(df.notnull())

# .fillna() - Fills missing values with specified value
print("\nFilling missing values with 0:")
print(df.fillna(0))

# .replace() - Replaces specified values in the DataFrame
print("\nReplacing NaN values with -1:")
print(df.replace(np.nan, -1))

# .interpolate() - Interpolates missing values in the DataFrame
print("\nInterpolating missing values:")
print(df.interpolate())

# .dropna() - Drops missing values from the DataFrame
print("\nDropping rows with missing values:")
print(df.dropna())

Checking for missing values in the DataFrame:
       A      B      C
0  False   True  False
1   True  False  False
2  False   True  False
3  False  False  False
4  False  False  False

Checking for non-missing values in the DataFrame:
       A      B     C
0   True  False  True
1  False   True  True
2   True  False  True
3   True   True  True
4   True   True  True

Filling missing values with 0:
     A    B  C
0  1.0  0.0  1
1  0.0  2.0  2
2  3.0  0.0  3
3  4.0  4.0  4
4  5.0  5.0  5

Replacing NaN values with -1:
     A    B  C
0  1.0 -1.0  1
1 -1.0  2.0  2
2  3.0 -1.0  3
3  4.0  4.0  4
4  5.0  5.0  5

Interpolating missing values:
     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  3.0  3.0  3
3  4.0  4.0  4
4  5.0  5.0  5

Dropping rows with missing values:
     A    B  C
3  4.0  4.0  4
4  5.0  5.0  5

In [45]:
# Create a sample DataFrame
data = {'A': [1, 2, 3, 4, 5],
        'B': ['a', 'b', 'c', 'd', 'e']}
df = pd.DataFrame(data)

# Using .query() to filter rows based on a condition
filtered_df = df.query('A > 2')
print("Filtered DataFrame where column 'A' is greater than 2:")
print(filtered_df)

Filtered DataFrame where column 'A' is greater than 2:
   A  B
2  3  c
3  4  d
4  5  e

**Loops and Dataframes**

In [46]:
# Example DataFrame
data = {'A': [1, 2, 3],
        'B': [4, 5, 6],
        'C': [7, 8, 9]}
df = pd.DataFrame(data)

# Using .iterrows() to iterate over rows
print("Using .iterrows() to iterate over rows:")
for index, row in df.iterrows():
    print(f"Row index: {index}, values: {row['A']}, {row['B']}, {row['C']}")

# Using .itertuples() to iterate over rows as namedtuples
print("\nUsing .itertuples() to iterate over rows as namedtuples:")
for row in df.itertuples():
    print(f"Index: {row.Index}, values: {row.A}, {row.B}, {row.C}")

Using .iterrows() to iterate over rows:
Row index: 0, values: 1, 4, 7
Row index: 1, values: 2, 5, 8
Row index: 2, values: 3, 6, 9

Using .itertuples() to iterate over rows as namedtuples:
Index: 0, values: 1, 4, 7
Index: 1, values: 2, 5, 8
Index: 2, values: 3, 6, 9

## 14.4. Filtering dataframes

In [47]:
# Create a sample DataFrame
data = {'A': [1, 2, 3, 4, 5],
        'B': ['a', 'b', 'c', 'd', 'e']}
df = pd.DataFrame(data)

In [48]:
# Filtering rows based on a single condition:
# Filter rows where column 'A' is greater than 2

filtered_df = df[df['A'] > 2]
print(filtered_df)

   A  B
2  3  c
3  4  d
4  5  e

In [49]:
# Filtering rows based on multiple conditions:
# Filter rows where column 'A' is greater than 2 and column 'B' is 'c'
filtered_df = df[(df['A'] > 2) & (df['B'] == 'c')]
print(filtered_df)

   A  B
2  3  c

In [50]:
# Filtering rows based on a condition using `.loc`:
# Filter rows where column 'A' is greater than 2
filtered_df = df.loc[df['A'] > 2]
print(filtered_df)

   A  B
2  3  c
3  4  d
4  5  e

In [51]:
# Filtering rows based on a condition and selecting specific columns:
# Filter rows where column 'A' is greater than 2 and select only columns 'A' and 'B'
filtered_df = df.loc[df['A'] > 2, ['A', 'B']]
print(filtered_df)

   A  B
2  3  c
3  4  d
4  5  e

## 14.5. `pandas` series

**Series.** A `pandas` Series is like a column of a dataframe.

We can construct Series of `pandas` from a one-dimensional list

In [52]:
a = [1, 2, 3, 4, 5]
my_series = pd.Series(a)
print(my_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

**Note.** If we do not specify anything, by default the labels of the Series entries correspond to the index they occupy. Let's remember that in `Python` the indices start with 0.

These tags can be used to access a specific value

In [53]:
print(my_series[1])

2

When we create a Series, we can modify its labels with the `index` parameter:

In [54]:
my_series = pd.Series(a, index = ["a", "b", "c", "d", "e"])
print(my_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

Now, to access a particular entry, we will do so with the new tags:

In [55]:
print(my_series["c"])

3

We can also create Series from dictionaries. In this case, the keys will correspond to the series labels, and the dictionary values will correspond to the values taken by the Series entries.

In [56]:
videos = {"day1": 5, "day2": 9, "day3": 7, "day4": 6, "day5": 8}
my_series = pd.Series(videos)
print(my_series)

day1    5
day2    9
day3    7
day4    6
day5    8
dtype: int64

## 14.6. DataFrame Combining Methods

| Method              | Description                                                                                   |
|---------------------|-----------------------------------------------------------------------------------------------|
| `join()`            | Combines DataFrames using columns as join keys.                                               |
| `merge()`           | Combines DataFrames using one or more columns as join keys.                                   |
| `concat()`          | Concatenates DataFrames along a specific axis (default is along rows).                        |
| `merge_ordered()`   | Merges DataFrames with ordered indices.                                                       |
| `merge_asof()`      | Merges DataFrames using an asof merge of the keys.                                            |
| `combine_first()`   | Combines DataFrames with priority given to one of the DataFrames.                             |
| `update()`          | Updates one DataFrame with values from another DataFrame, using non-NA values from the other. |

In [2]:
# Sample DataFrames
df1 = pd.DataFrame({'A': [1, 2, 3],
                    'B': ['a', 'b', 'c']})

df2 = pd.DataFrame({'A': [4, 5, 6],
                    'B': ['d', 'e', 'f']})

# join()
result_join = df1.join(df2, lsuffix='_left', rsuffix='_right')
print("Join result:")
print(result_join)

# merge()
result_merge = pd.merge(df1, df2, on='A')
print("\nMerge result:")
print(result_merge)

# concat()
result_concat = pd.concat([df1, df2], axis=0)
print("\nConcatenation result:")
print(result_concat)

# merge_ordered()
df3 = pd.DataFrame({'A': [1, 3, 5],
                    'B': ['a', 'c', 'e']})
df4 = pd.DataFrame({'A': [1, 2, 4],
                    'C': ['x', 'y', 'z']})

result_merge_ordered = pd.merge_ordered(df3, df4, on='A')
print("\nMerge ordered result:")
print(result_merge_ordered)

# merge_asof()
df_left = pd.DataFrame({'time': [1, 2, 3, 4, 5],
                        'value': [10, 20, 30, 40, 50]})
df_right = pd.DataFrame({'time': [1, 2, 3, 6],
                         'value': [15, 25, 35, 45]})

result_merge_asof = pd.merge_asof(df_left, df_right, on='time')
print("\nMerge asof result:")
print(result_merge_asof)

# combine_first()
df5 = pd.DataFrame({'A': [1, 2, 3],
                    'B': [None, 'b', 'c']})
df6 = pd.DataFrame({'A': [1, 2, 3],
                    'B': ['x', 'y', 'z']})

result_combine_first = df5.combine_first(df6)
print("\nCombine first result:")
print(result_combine_first)

# update()
df7 = pd.DataFrame({'A': [1, 2, 3],
                    'B': [4, 5, 6]})
df8 = pd.DataFrame({'A': [1, 2],
                    'B': [7, 8]})

df7.update(df8)
print("\nUpdate result:")
print(df7)

Join result:
   A_left B_left  A_right B_right
0       1      a        4       d
1       2      b        5       e
2       3      c        6       f

Merge result:
Empty DataFrame
Columns: [A, B_x, B_y]
Index: []

Concatenation result:
   A  B
0  1  a
1  2  b
2  3  c
0  4  d
1  5  e
2  6  f

Merge ordered result:
   A    B    C
0  1    a    x
1  2  NaN    y
2  3    c  NaN
3  4  NaN    z
4  5    e  NaN

Merge asof result:
   time  value_x  value_y
0     1       10       15
1     2       20       25
2     3       30       35
3     4       40       35
4     5       50       35

Combine first result:
   A  B
0  1  x
1  2  b
2  3  c

Update result:
   A  B
0  1  7
1  2  8
2  3  6

## 14.7. Problems

### 14.7.1. Problem 1

Create a text file called `test.txt` and write a couple of lines into it. Read the file `test.txt` created above and store all the contents of the file in a variable named `content`. Read the contents of the file line by line and store it in a list, use `f.readlines()` to do this.

In [57]:
%cd C:/Users/RJKANG/Desktop/quant/Statistical Learning/Introduction to Statistical Learning/

C:\Users\RJKANG\Desktop\quant\Statistical Learning\Introduction to Statistical Learning

In [58]:
f = open("test.txt", "w")
for i in range(5):
    f.write(f"This is line {i}\n")
    
f.close()

In [59]:
f = open("./test.txt", "r")
content = f.read()
f.close()
print(content)

This is line 0
This is line 1
This is line 2
This is line 3
This is line 4

In [60]:
f = open("./test.txt", "r")
contents = f.readlines()
f.close()
print(contents)

['This is line 0\n', 'This is line 1\n', 'This is line 2\n', 'This is line 3\n', 'This is line 4\n']

In [61]:
type(contents)

list

### 14.7.2. Problem 2

Store an array `[[1.20, 2.20, 3.00], [4.14, 5.65, 6.42]]` in a file called `my_array.txt` and save it in a variable called `my_arr`.

In [62]:
import numpy as np

In [63]:
arr = np.array([[1.20, 2.20, 3.00], [4.14, 5.65, 6.42]])
arr

array([[1.2 , 2.2 , 3.  ],
       [4.14, 5.65, 6.42]])

In [64]:
np.savetxt("my_arr.txt", arr, fmt="%.2f", header = "Col1 Col2 Col3")

In [65]:
f = open("./my_arr.txt", "r")
content = f.read()
f.close()
print(content)

# Col1 Col2 Col3
1.20 2.20 3.00
4.14 5.65 6.42

### 14.7.3. Problem 3

Generate a `.csv` type file with 100 rows and 5 columns of random number data. Read the file using the `np.loadtxt` function.

In [66]:
data = np.random.random((100,5))

In [67]:
np.savetxt("problem3_dataframe1.csv", data, fmt = "%.2f", delimiter=",", header = "c1, c2, c3, c4, c5")

In [68]:
np.savetxt("problem3_dataframe1.csv", data, fmt = "%.2f",
           delimiter=",", header = "c1, c2, c3, c4, c5")

In [69]:
my_csv = np.loadtxt("./problem3_dataframe.csv", delimiter=",")
my_csv[:5, :]

array([[0.62, 0.33, 0.54, 0.04, 0.17],
       [0.12, 0.72, 0.52, 0.08, 0.79],
       [0.9 , 0.87, 0.19, 0.95, 1.  ],
       [0.72, 0.28, 0.51, 0.67, 0.9 ],
       [0.95, 0.11, 0.41, 0.88, 0.69]])

### 14.7.4. Problem 4

Create a dictionary and save it to a pickle file on disk. Next, load the pickle file that was just saved to disk using the `pickle.load` function.

In [70]:
import pickle

In [71]:
dict_a = {"A":0, "B":1, "C":2}
pickle.dump(dict_a, open("test.pkl", "wb"))

In [72]:
my_dict = pickle.load(open("./test.pkl", "rb"))
my_dict

{'A': 0, 'B': 1, 'C': 2}

### 14.7.5. Problem 5

Create a dictionary and save it to a JSON file on disk. Load the newly saved JSON file to disk after using the `json.load` function.

In [73]:
import json

In [74]:
school = {
"school": "UC Berkeley",
"address": {
    "city": "Berkeley",
    "state": "California",
    "postal": "94720"
},
    
"list":[
    "student 1",
    "student 2",
    "student 3"
    ],
"array":[1, 2, 3]
}
json.dump(school, open("school.json", "w"))

In [75]:
my_school = json.load(open("./school.json", "r"))
my_school

{'school': 'UC Berkeley',
 'address': {'city': 'Berkeley', 'state': 'California', 'postal': '94720'},
 'list': ['student 1', 'student 2', 'student 3'],
 'array': [1, 2, 3]}

### 14.7.6. Problem 6

Create a dataframe with 10 rows and 5 columns with the following characteristics:

- The first column will be `word` and will contain 10 words.
- The second column will be `length` and will contain the length of each word.
- The third column will be `start` and will contain the first letter of each word.
- The fourth column will be 'end' and will contain the last letter of each word.
- The fifth column will be `isPalindrome} and will contain boolean values indicating whether or not each word is a palindrome.

Next, transform the `word` column into the row names using the `.set_index()` method. Finally, calculate the dimensions of the dataframe.

In [76]:
def is_palindrome(word):
     """
     Returns whether the word word is palindrome.
     Args:
         word: Word in string format
     Returns:
         isPalindrome: Boolean
     """
     word = word.lower()
     l = []
     isPalindrome = True
     for c in word:
         l.append(c)
     n = len(l)
     for i in range(int(n / 2)):
         if l[i] != l[n - (i + 1)]:
             isPalindrome = False
     return isPalindrome

In [77]:
words = ["madam", "wing", "bed", "hard", "good", "kayak", "level", "rotor", "mystery", "civic"]
data = {"word": words,
         "length": map(len, words),
         "start": map(lambda w: w[0], words),
         "end": map(lambda w: w[-1], words),
         "isPalindrome": map(is_palindrome, words)}

import pandas as pd
words = pd.DataFrame(data)

In [78]:
words

      word  length start end  isPalindrome
0    madam       5     m   m          True
1     wing       4     w   g         False
2      bed       3     b   d         False
3     hard       4     h   d         False
4     good       4     g   d         False
5    kayak       5     k   k          True
6    level       5     l   l          True
7    rotor       5     r   r          True
8  mystery       7     m   y         False
9    civic       5     c   c          True

In [79]:
words = words.set_index("word")

In [80]:
words.index.names = [None]
words.head()

       length start end  isPalindrome
madam       5     m   m          True
wing        4     w   g         False
bed         3     b   d         False
hard        4     h   d         False
good        4     g   d         False

In [81]:
words.shape

(10, 4)

### 14.7.7. Problem 7

From the `words` dataframe created in problem 7, display each column separately with a `for` loop. Finally, keep the last 3 columns, and save this new subdataframe in a new variable, `words2`, so as not to modify the original dataframe.

In [82]:
def is_palindrome(word):
     """
     Returns whether the word word is palindrome.
     Args:
         word: Word in string format
     Returns:
         isPalindrome: Boolean
     """
     word = word.lower()
     l = []
     isPalindrome = True
     for c in word:
         l.append(c)
     n = len(l)
     for i in range(int(n / 2)):
         if l[i] != l[n - (i + 1)]:
             isPalindrome = False
     return isPalindrome

words = ["sun", "wing", "bed", "hard", "good", "kayak", "tide", "rotor", "mystery", "snuggle"]
data = {"word": words,
         "length": map(len, words),
         "start": map(lambda w: w[0], words),
         "end": map(lambda w: w[-1], words),
         "isPalindrome": map(is_palindrome, words)}

import pandas as pd
words = pd.DataFrame(data)
words = words.set_index("word")
words.index.names = [None]

In [83]:
words.head()

      length start end  isPalindrome
sun        3     s   n         False
wing       4     w   g         False
bed        3     b   d         False
hard       4     h   d         False
good       4     g   d         False

In [84]:
for col in list(words):
    print("=== {} ===".format(col.upper()))
    print(words[col], end = "\n\n\n")

=== LENGTH ===
sun        3
wing       4
bed        3
hard       4
good       4
kayak      5
tide       4
rotor      5
mystery    7
snuggle    7
Name: length, dtype: int64


=== START ===
sun        s
wing       w
bed        b
hard       h
good       g
kayak      k
tide       t
rotor      r
mystery    m
snuggle    s
Name: start, dtype: object


=== END ===
sun        n
wing       g
bed        d
hard       d
good       d
kayak      k
tide       e
rotor      r
mystery    y
snuggle    e
Name: end, dtype: object


=== ISPALINDROME ===
sun        False
wing       False
bed        False
hard       False
good       False
kayak       True
tide       False
rotor       True
mystery    False
snuggle    False
Name: isPalindrome, dtype: bool

In [85]:
words2 = words.iloc[:, 1:]
words2.head()

     start end  isPalindrome
sun      s   n         False
wing     w   g         False
bed      b   d         False
hard     h   d         False
good     g   d         False

### 14.7.8. Problem 8

From the `words` dataframe created in problem 7, display the first 5 rows, the last 5 rows and then save a copy in the `words_copy` variable. Finally, modify the column names of `words_copy` to "Length", "Start", "End", "Palindrome".

In [86]:
def is_palindrome(word):
     """
     Returns whether the word word is palindrome.
     Args:
         word: Word in string format
     Returns:
         isPalindrome: Boolean
     """
     word = word.lower()
     l = []
     isPalindrome = True
     for c in word:
         l.append(c)
     n = len(l)
     for i in range(int(n / 2)):
         if l[i] != l[n - (i + 1)]:
             isPalindrome = False
     return isPalindrome

words = ["sun", "wing", "bed", "hard", "good", "kayak", "tide", "rotor", "mystery", "snuggle"]
data = {"word": words,
         "length": map(len, words),
         "start": map(lambda w: w[0], words),
         "end": map(lambda w: w[-1], words),
         "isPalindrome": map(is_palindrome, words)}

import pandas as pd
words = pd.DataFrame(data)
words = words.set_index("word")
words.index.names = [None]

In [87]:
words.head(5)

      length start end  isPalindrome
sun        3     s   n         False
wing       4     w   g         False
bed        3     b   d         False
hard       4     h   d         False
good       4     g   d         False

In [88]:
words.tail(5)

         length start end  isPalindrome
kayak         5     k   k          True
tide          4     t   e         False
rotor         5     r   r          True
mystery       7     m   y         False
snuggle       7     s   e         False

In [89]:
words_copy = words.copy()
words_copy = words_copy.rename(columns = {"length": "Longitud",
                             "start": "Principio",
                             "end": "Fin",
                             "isPalindrome": "Palindromo"})
words_copy

         Longitud Principio Fin  Palindromo
sun             3         s   n       False
wing            4         w   g       False
bed             3         b   d       False
hard            4         h   d       False
good            4         g   d       False
kayak           5         k   k        True
tide            4         t   e       False
rotor           5         r   r        True
mystery         7         m   y       False
snuggle         7         s   e       False

In [90]:
words

         length start end  isPalindrome
sun           3     s   n         False
wing          4     w   g         False
bed           3     b   d         False
hard          4     h   d         False
good          4     g   d         False
kayak         5     k   k          True
tide          4     t   e         False
rotor         5     r   r          True
mystery       7     m   y         False
snuggle       7     s   e         False

### 14.7.9. Problem 9

Display the rows of the `words` dataframe created in problem 7 with the following format: `The word {rowidentifier} {yes/no} is a string of {length} letters} `.

In [91]:
def is_palindrome(word):
     """
     Returns whether the word word is palindrome.
     Args:
         word: Word in string format
     Returns:
         isPalindrome: Boolean
     """
     word = word.lower()
     l = []
     isPalindrome = True
     for c in word:
         l.append(c)
     n = len(l)
     for i in range(int(n / 2)):
         if l[i] != l[n - (i + 1)]:
             isPalindrome = False
     return isPalindrome

words = ["sun", "wing", "bed", "hard", "good", "kayak", "tide", "rotor", "mystery", "snuggle"]
data = {"word": words,
         "length": map(len, words),
         "start": map(lambda w: w[0], words),
         "end": map(lambda w: w[-1], words),
         "isPalindrome": map(is_palindrome, words)}

import pandas as pd
words = pd.DataFrame(data)
words = words.set_index("word")
words.index.names = [None]

In [92]:
for row in words.itertuples():
     print("The word {}{} is a palindrome of {} letters."
         .format(row[0], "" if row[4] else " no", row[1]))

The word sun no is a palindrome of 3 letters.
The word wing no is a palindrome of 4 letters.
The word bed no is a palindrome of 3 letters.
The word hard no is a palindrome of 4 letters.
The word good no is a palindrome of 4 letters.
The word kayak is a palindrome of 5 letters.
The word tide no is a palindrome of 4 letters.
The word rotor is a palindrome of 5 letters.
The word mystery no is a palindrome of 7 letters.
The word snuggle no is a palindrome of 7 letters.

### 14.7.10. Problem 10

Load a csv from a [url](https://gist.githubusercontent.com/jncraton/68beb88e6027d9321373/raw/381dcf8c0d4534d420d2488b9c60b1204c9f4363/starwars.csv) and then remove all `NA` values.

In [93]:
import pandas as pd
sw = pd.read_csv("https://gist.githubusercontent.com/jncraton/68beb88e6027d9321373/\
raw/381dcf8c0d4534d420d2488b9c60b1204c9f4363/starwars.csv")

In [94]:
sw.shape

(508, 17)

In [95]:
sw = sw.dropna()

In [96]:
sw.shape

(155, 17)

### 14.7.11. Problem 11

From the `words` dataframe created in problem 7, transform the `start` column to a dataframe to iterate over its rows. Next, transform the `length` column into a list to remove one of its entries with the `.remove()` method.

In [97]:
def is_palindrome(word):
     """
     Returns whether the word word is palindrome.
     Args:
         word: Word in string format
     Returns:
         isPalindrome: Boolean
     """
     word = word.lower()
     l = []
     isPalindrome = True
     for c in word:
         l.append(c)
     n = len(l)
     for i in range(int(n / 2)):
         if l[i] != l[n - (i + 1)]:
             isPalindrome = False
     return isPalindrome

words = ["sun", "wing", "bed", "hard", "good", "kayak", "tide", "rotor", "mystery", "snuggle"]
data = {"word": words,
         "length": map(len, words),
         "start": map(lambda w: w[0], words),
         "end": map(lambda w: w[-1], words),
         "isPalindrome": map(is_palindrome, words)}

import pandas as pd
words = pd.DataFrame(data)
words = words.set_index("word")
words.index.names = [None]

In [98]:
start_df = words["start"].to_frame()
for row in start_df.itertuples():
    print("La palabra {} empieza por {}".format(row[0], row[1]))

La palabra sun empieza por s
La palabra wing empieza por w
La palabra bed empieza por b
La palabra hard empieza por h
La palabra good empieza por g
La palabra kayak empieza por k
La palabra tide empieza por t
La palabra rotor empieza por r
La palabra mystery empieza por m
La palabra snuggle empieza por s

In [99]:
length_list = words["length"].tolist()
print(length_list)

[3, 4, 3, 4, 4, 5, 4, 5, 7, 7]

In [100]:
length_list.remove(3)

In [101]:
print(length_list)

[4, 3, 4, 4, 5, 4, 5, 7, 7]