## 14.8. `Python` & `SQL` integration

### 14.8.1. Database and Relational Database definition

1. **Database**: A database is an organized collection of data that is stored and can be electronically accessed from a computer system. It is designed to allow for efficient retrieval, updating, and management of that data. Databases can vary in size and complexity, from simple datasets to complex systems used in large enterprises and organizations.

2. **Relational Database**: A relational database is a specific type of database that organizes data into related tables. These tables are comprised of rows and columns, where each row represents an individual instance of data and each column represents a specific attribute of that data. The relationship between tables is established through primary and foreign keys, enabling efficient and consistent querying and manipulation of the data. Relational databases follow the principles of the relational model proposed by Edgar F. Codd in the 1970s and are widely used in business and software applications due to their flexibility and scalability.

### 14.8.2. Database Management System (DBMS):

A database management system is software that allows users to interact with a database, providing functions to create, modify, organize, and query data efficiently. These systems handle tasks such as data storage, retrieval, and security, as well as transaction management to ensure the integrity and consistency of the data. DBMS can be of different types, including relational systems, NoSQL database systems, object-oriented systems, among others.

1. [**SQLite**](https://www.sqlite.org/): A lightweight, open-source relational database management system that is implemented as a library within applications. SQLite is known for its ease of use, portability, and ability to be embedded into applications without requiring a separate database server. It is commonly used in mobile applications, web browsers, and other environments where a simple and efficient local database is required.

2. **MySQL**: An open-source relational database management system widely used for its performance, scalability, and ease of use.

3. **PostgreSQL**: Another open-source relational database management system known for its robustness, standards compliance, and advanced features such as support for custom data types and extensions.

4. **Oracle Database**: A relational database management system developed by Oracle Corporation. It is known for its scalability, reliability, and extensive capabilities for enterprises.

5. **Microsoft SQL Server**: A relational database management system developed by Microsoft. It is widely used in enterprise environments and tightly integrates with other Microsoft products.

6. **MongoDB**: A document-oriented NoSQL database management system. It is known for its schema flexibility and ability to handle unstructured or semi-structured data.

7. **Redis**: A NoSQL database management system commonly used as an in-memory database or as a data structure store in memory to accelerate application performance.

These are some examples of database management systems, each with its own features and specific use cases.

### 14.8.3. Primary and Foreign keys

**Primary Keys**:
- Unique: Each value in the primary key must be unique within the table.
- Immutable: Primary key values should not change once they are set.
- Never null: Primary key values cannot be null.

**Foreign Keys**:
- Do not have to be unique: Foreign key values can repeat within a table.
- Multiple foreign keys in an entity: A table can contain multiple foreign keys referencing different tables.
- Never null: Foreign key values must reference an existing value in the referenced table.

**Composite Primary Keys**:
- Used when two or more attributes are required to identify a record in a table.
- Used when it is not possible to take a single attribute as a primary key.
- Some rules for creating a composite primary key include:
  1. Use the minimum number of attributes possible.
  2. Avoid using attributes that are prone to change.

These definitions and considerations are important for proper design and implementation of relational databases.

We are going to use `SQLite` as a database manager integrating it with `Python`

In [1]:
# Commands to run scripts in SLite

# Connect to sqlite: `sqlite3`
# Open sqlite browser from terminal: `sqlitebrowser`
# Run scripts: `.read file.sql`
# Quit sqlite3: `.quit`, `.exit` or `'ctrl + d'`
# Clear the console: ``ctrl + l'`
# After a statement in SQL you must place `;`
# Create or connect to a database: `sqlite3 file.db` (or connect to sqlite and run `.open file.db`

In [2]:
# To integrate SQLite with Python we import the libraries
import sqlite3
import pandas as pd

In [3]:
# Connect to the database (will create the file if it doesn't exist)
conn = sqlite3.connect('example.db')

# Create a cursor to execute SQL commands
cursor = conn.cursor()

# Drop the table if it exists
cursor.execute("DROP TABLE IF EXISTS users")

# Create a table named "users"
cursor.execute("""CREATE TABLE users
                  (id INTEGER PRIMARY KEY, name TEXT, age INTEGER)""")

# Insert some data into the table
cursor.execute("""INSERT INTO users (name, age) VALUES ('John', 30)""")
cursor.execute("""INSERT INTO users (name, age) VALUES ('Mary', 25)""")
cursor.execute("""INSERT INTO users (name, age) VALUES ('Peter', 40)""")

# Commit the changes and close the connection
conn.commit()
conn.close()

print("Database created and populated successfully.")

Database created and populated successfully.

In [4]:
# Connect to the database
conn = sqlite3.connect('example.db')

# Create a cursor to execute SQL commands
cursor = conn.cursor()

# Execute a query to retrieve all records from the "users" table
cursor.execute("""SELECT * FROM users""")

# Fetch all the results from the query
rows = cursor.fetchall()

# Print the results
for row in rows:
    print(row)

# Close the connection
conn.close()

(1, 'John', 30)
(2, 'Mary', 25)
(3, 'Peter', 40)

We could also have created and populated the database from a sql script and then run it from Python

In [5]:
# Connect to the database and create a cursor
conn = sqlite3.connect('example_script.db')
cursor = conn.cursor()

# Read the content of the SQL script from the file
with open('create_and_populate.sql', 'r') as script_file:
    sql_script = script_file.read()

# Drop the table if it exists
cursor.execute("DROP TABLE IF EXISTS users")

# Execute the SQL script
cursor.executescript(sql_script)

# Commit the changes and close the connection
conn.commit()
conn.close()

print("Script executed successfully.")

Script executed successfully.

In [6]:
# Connect to the database
conn = sqlite3.connect('example_script.db')

# Create a cursor to execute SQL commands
cursor = conn.cursor()

# Execute a query to retrieve all records from the "users" table
cursor.execute("""SELECT * FROM users""")

# Fetch all the results from the query
rows = cursor.fetchall()

# Print the results
for row in rows:
    print(row)

# Close the connection
conn.close()

(1, 'John', 30)
(2, 'Mary', 25)
(3, 'Peter', 40)

### 14.8.4. Data types in `SQLite`

The data types in `SQLite` are in the following table:

| Data Type    | Description                                                                                            |
|--------------|--------------------------------------------------------------------------------------------------------|
| `NULL`       | The `NULL` type represents a missing or unknown value.                                                 |
| `INTEGER`    | The `INTEGER` type is used for storing whole numbers, either signed or unsigned.                       |
| `REAL`       | The `REAL` type is used for storing floating-point numbers.                                            |
| `TEXT`       | The `TEXT` type is used for storing alphanumeric or character data.                                    |
| `BLOB`       | The `BLOB` type is used for storing binary data such as images, documents, or other non-textual data.  |
| `DATE`       | The `DATE` type is used for storing dates in the format 'YYYY-MM-DD'.                                  |
| `TIME`       | The `TIME` type is used for storing times in the format 'HH:MM:SS'.                                    |
| `DATETIME`   | The `DATETIME` type is used for storing date and time values in the format 'YYYY-MM-DD HH:MM:SS'.      |

### 14.8.5. Most common queries in `SQL`

| Command   | Description                                                                                           |
|-----------|-------------------------------------------------------------------------------------------------------|
| `CREATE`  | Used to create new database objects such as tables, indexes, or views in SQLite.                      |
| `ALTER`   | Used to modify existing database objects such as tables by adding, modifying, or dropping columns.     |
| `DROP`    | Used to delete existing database objects such as tables, indexes, or views from the database.          |
| `TRUNCATE`| Used to delete all rows from a table in SQLite, without removing the table structure.                 |
| `INSERT`  | Used to add new rows of data into a table in SQLite.                                                   |
| `UPDATE`  | Used to modify existing data in a table in SQLite.                                                      |
| `DELETE`  | Used to remove existing rows from a table in SQLite.                                                    |
| `COMMIT`  | Used to permanently save the changes made within a transaction to the database.                        |
| `ROLLBACK`| Used to discard any changes made within a transaction and revert the database to its previous state.   |
| `SAVEPOINT`| Used to set a named point within a transaction to which you can later roll back.                       |

In [7]:
# Connect to SQLite database (create if not exists)
conn = sqlite3.connect('example.db')
cur = conn.cursor()

# CREATE
cur.execute("""CREATE TABLE IF NOT EXISTS Students (
                    id INTEGER PRIMARY KEY,
                    name TEXT,
                    age INTEGER
                );""")

# INSERT
cur.execute("INSERT INTO Students (name, age) VALUES (?, ?);", ('Alice', 20))
cur.execute("INSERT INTO Students (name, age) VALUES (?, ?);", ('Bob', 22))
conn.commit()

cur.execute("SELECT * FROM Students;")
print("SELECT:", cur.fetchall())

# UPDATE
cur.execute("UPDATE Students SET age=? WHERE name=?;", (21, 'Alice'))
conn.commit()

cur.execute("SELECT * FROM Students;")
print("SELECT:", cur.fetchall())

# DELETE
cur.execute("DELETE FROM Students WHERE name=?;", ('Bob',))
conn.commit()

# DROP
cur.execute("DROP TABLE IF EXISTS Students;")
conn.commit()

# Close connection
conn.close()

SELECT: [(1, 'Alice', 20), (2, 'Bob', 22)]
SELECT: [(1, 'Alice', 21), (2, 'Bob', 22)]

[**Northwind Database**](https://en.wikiversity.org/wiki/Database_Examples/Northwind#SQL_Scripts): The Northwind database is a sample database that has been widely used in the industry and software development community. Originally created by Microsoft, it serves as a demonstration of the capabilities of Microsoft Access and Microsoft SQL Server. Northwind simulates a database for a fictional company that sells products to customers and manages orders, inventory, employees, etc.

The Northwind database contains several tables representing different aspects of a company, such as products, customers, orders, employees, suppliers, categories, etc. It is commonly used for learning, demonstration, and testing purposes in database and software development applications and courses.

Northwind has been adapted for various database management systems, including Microsoft SQL Server, MySQL, PostgreSQL, SQLite, among others. Versions of Northwind may vary slightly depending on the database management system used, but they maintain the same basic structure and sample data.

In summary, the Northwind database is a useful tool for practicing and learning about database design and management, as well as for developing and testing applications that require a sample database.

![northwind_er_diagram](northwind_er_diagram.png)

**Northwind Entity-Relation Diagram**

We run the northwind_script.sql script to create and populate the Northwind database

In [8]:
# Connect to database
conn = sqlite3.connect('Northwind.db')

# Create a cursor to execute SQL commands
cursor = conn.cursor()

# Read the content of the SQL script from the file
with open('northwind_script.sql', 'r') as script_file:
     sql_script = script_file.read()

# Run the SQL script
cursor.executescript(sql_script)

# Save changes and close the connection
conn.commit()
conn.close()

print("Script executed successfully. Northwind database has been created.")

Script executed successfully. Northwind database has been created.

We can transform database tables into pandas dataframes

In [9]:
# Connect to the Northwind database
conn = sqlite3.connect('Northwind.db')

query = """SELECT * FROM Customers;"""

# Read the Customers table into a dataframe
customers_df = pd.read_sql(query, conn)

# Display the first few rows of the dataframe
print("Head of Customers table:")
customers_df.head()

Head of Customers table:

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la ConstituciÃ³n 2222,MÃ©xico D.F.,5021,Mexico
2,3,Antonio Moreno TaquerÃ­a,Antonio Moreno,Mataderos 2312,MÃ©xico D.F.,5023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbkÃ¶p,Christina Berglund,BerguvsvÃ¤gen 8,LuleÃ¥,S-958 22,Sweden

From now on, we will use this database to perform the rest of the most common queries in `SQL`

| Command    | Description                                          |
|------------|------------------------------------------------------|
| `SELECT`   | Retrieves data from one or more tables.              |
| `SELECT TOP` | Retrieves a specified number of records from the beginning of a result set. |
| `FROM`     | Specifies the table(s) from which to retrieve data.  |
| `WHERE`    | Filters data based on specified criteria.            |
| `LIKE`     | Specifies a pattern to match in a WHERE clause.      |
| `NOT LIKE` | Specifies a pattern that should not be matched in a WHERE clause. |
| `GROUP BY` | Groups rows that have the same values into summary rows, often used with aggregate functions. |
| `HAVING`   | Filters groups based on specified criteria, similar to WHERE but used with GROUP BY. |
| `ORDER BY` | Sorts the result set in ascending or descending order. |
| `ORDER`    | Specifies the sort order, either ASC (ascending) or DESC (descending). |
| `OFFSET`   | Skips a specified number of rows from the beginning of the result set. |
| `DISTINCT` | Returns unique values in the result set, eliminating duplicate rows. |

In [10]:
# Connect to the Northwind database
conn = sqlite3.connect('northwind.db')

# Example of SELECT
df_select = pd.read_sql_query("""
    SELECT * FROM Customers;
""", conn)

# Example of SELECT TOP
df_select_top = pd.read_sql_query("""
    SELECT * FROM Customers LIMIT 5;
""", conn)

# Example of FROM and WHERE
df_where = pd.read_sql_query("""
    SELECT * FROM Orders WHERE CustomerID = 3;
""", conn)

# Example of LIKE
df_like = pd.read_sql_query("""
    SELECT * FROM Employees WHERE LastName LIKE '%a%';
""", conn)

# Example of NOT LIKE
df_not_like = pd.read_sql_query("""
    SELECT * FROM Employees WHERE LastName NOT LIKE '%a%';
""", conn)

# Example of GROUP BY and HAVING
df_group_having = pd.read_sql_query("""
    SELECT CustomerID, COUNT(*) as OrderCount FROM Orders GROUP BY CustomerID HAVING OrderCount > 5;
""", conn)

# Example of ORDER BY
df_order_by = pd.read_sql_query("""
    SELECT * FROM Customers ORDER BY Country ASC;
""", conn)

# Example of OFFSET
df_offset = pd.read_sql_query("""
    SELECT * FROM Customers ORDER BY CustomerID LIMIT 5 OFFSET 5;
""", conn)

# Example of DISTINCT
df_distinct = pd.read_sql_query("""
    SELECT DISTINCT Country FROM Customers;
""", conn)

# Close the connection
conn.close()

In [11]:
# Display dataframe
print("DataFrame for SELECT:")
df_select.head()

DataFrame for SELECT:

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la ConstituciÃ³n 2222,MÃ©xico D.F.,5021,Mexico
2,3,Antonio Moreno TaquerÃ­a,Antonio Moreno,Mataderos 2312,MÃ©xico D.F.,5023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbkÃ¶p,Christina Berglund,BerguvsvÃ¤gen 8,LuleÃ¥,S-958 22,Sweden

In [12]:
# Display dataframe
print("\nDataFrame for SELECT TOP:")
df_select_top.head()

DataFrame for SELECT TOP:

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,1,Alfreds Futterkiste,Maria Anders,Obere Str. 57,Berlin,12209,Germany
1,2,Ana Trujillo Emparedados y helados,Ana Trujillo,Avda. de la ConstituciÃ³n 2222,MÃ©xico D.F.,5021,Mexico
2,3,Antonio Moreno TaquerÃ­a,Antonio Moreno,Mataderos 2312,MÃ©xico D.F.,5023,Mexico
3,4,Around the Horn,Thomas Hardy,120 Hanover Sq.,London,WA1 1DP,UK
4,5,Berglunds snabbkÃ¶p,Christina Berglund,BerguvsvÃ¤gen 8,LuleÃ¥,S-958 22,Sweden

In [13]:
# Display dataframe
print("\nDataFrame for FROM and WHERE:")
df_where.head()

DataFrame for FROM and WHERE:

   OrderID  CustomerID  EmployeeID   OrderDate  ShipperID
0    10365           3           3  1996-11-27          2

In [14]:
# Display dataframe
print("\nDataFrame for LIKE:")
df_like.head()

DataFrame for LIKE:

,EmployeeID,LastName,FirstName,BirthDate,Photo,Notes
0,1,Davolio,Nancy,1968-12-08,EmpID1.pic,Education includes a BA in psychology from Col...
1,4,Peacock,Margaret,1958-09-19,EmpID4.pic,Margaret holds a BA in English literature from...
2,5,Buchanan,Steven,1955-03-04,EmpID5.pic,Steven Buchanan graduated from St. Andrews Uni...
3,6,Suyama,Michael,1963-07-02,EmpID6.pic,Michael is a graduate of Sussex University (MA...
4,8,Callahan,Laura,1958-01-09,EmpID8.pic,Laura received a BA in psychology from the Uni...

In [15]:
# Display dataframe
print("\nDataFrame for NOT LIKE:")
df_not_like.head()

DataFrame for NOT LIKE:

,EmployeeID,LastName,FirstName,BirthDate,Photo,Notes
0,2,Fuller,Andrew,1952-02-19,EmpID2.pic,Andrew received his BTS commercial and a Ph.D....
1,3,Leverling,Janet,1963-08-30,EmpID3.pic,Janet has a BS degree in chemistry from Boston...
2,7,King,Robert,1960-05-29,EmpID7.pic,Robert King served in the Peace Corps and trav...
3,9,Dodsworth,Anne,1969-07-02,EmpID9.pic,Anne has a BA degree in English from St. Lawre...
4,10,West,Adam,1928-09-19,EmpID10.pic,An old chum.

In [16]:
# Display dataframe
print("\nDataFrame for GROUP BY and HAVING:")
df_group_having.head()

DataFrame for GROUP BY and HAVING:

   CustomerID  OrderCount
0          20          10
1          37           6
2          63           7
3          65           7
4          75           6

In [17]:
# Display dataframe
print("\nDataFrame for ORDER BY:")
df_order_by.head()

DataFrame for ORDER BY:

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,12,Cactus Comidas para llevar,Patricio Simpson,Cerrito 333,Buenos Aires,1010,Argentina
1,54,OcÃ©ano AtlÃ¡ntico Ltda.,Yvonne Moncada,Ing. Gustavo Moncada 8585 Piso 20-A,Buenos Aires,1010,Argentina
2,64,Rancho grande,Sergio GutiÃ©rrez,Av. del Libertador 900,Buenos Aires,1010,Argentina
3,20,Ernst Handel,Roland Mendel,Kirchgasse 6,Graz,8010,Austria
4,59,Piccolo und mehr,Georg Pipps,Geislweg 14,Salzburg,5020,Austria

In [18]:
# Display dataframe
print("\nDataFrame for OFFSET:")
df_offset.head()

DataFrame for OFFSET:

,CustomerID,CustomerName,ContactName,Address,City,PostalCode,Country
0,6,Blauer See Delikatessen,Hanna Moos,Forsterstr. 57,Mannheim,68306,Germany
1,7,Blondel pÃ¨re et fils,FrÃ©dÃ©rique Citeaux,"24, place KlÃ©ber",Strasbourg,67000,France
2,8,BÃ³lido Comidas preparadas,MartÃ­n Sommer,"C/ Araquil, 67",Madrid,28023,Spain
3,9,Bon app'',Laurence Lebihans,"12, rue des Bouchers",Marseille,13008,France
4,10,Bottom-Dollar Marketse,Elizabeth Lincoln,23 Tsawassen Blvd.,Tsawassen,T2F 8M4,Canada

In [19]:
# Display dataframe
print("\nDataFrame for DISTINCT:")
df_distinct.head()

DataFrame for DISTINCT:

   Country
0  Germany
1   Mexico
2       UK
3   Sweden
4   France

Logical and comparison operators in `SQLite` are given in the following table:

| Operator | Description                        |
|----------|------------------------------------|
| `AND`    | Logical AND operator               |
| `OR`     | Logical OR operator                |
| `NOT`    | Logical NOT operator               |
| `=`      | Equal to operator                  |
| `<`      | Less than operator                 |
| `>`      | Greater than operator              |
| `<=`     | Less than or equal to operator     |
| `>=`     | Greater than or equal to operator  |
| `<>`     | Not equal to operator (alternative to `!=`) |

In [20]:
# Connect to the Northwind database
conn = sqlite3.connect('Northwind.db')

# Example of AND operator
df_and = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE Country = 'Germany' AND SupplierID > 10;
""", conn)

# Example of OR operator
df_or = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE Country = 'Germany' OR Country = 'USA';
""", conn)

# Example of NOT operator
df_not = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE NOT Country = 'Germany';
""", conn)

# Example of = operator
df_equal = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE City = 'Madrid';
""", conn)

# Example of < operator
df_less_than = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE SupplierID < 50;
""", conn)

# Example of > operator
df_greater_than = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE SupplierID > 30;
""", conn)

# Example of <= operator
df_less_than_or_equal = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE SupplierID <= 100;
""", conn)

# Example of >= operator
df_greater_than_or_equal = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE SupplierID >= 150;
""", conn)

# Example of <> (not equal) operator
df_not_equal = pd.read_sql_query("""
    SELECT * FROM Suppliers 
    WHERE Country <> 'USA';
""", conn)

# Close the connection
conn.close()

In [21]:
# Display dataframe
print("DataFrame for AND operator:")
df_and.head()

DataFrame for AND operator:

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,11,Heli SÃ¼ÃŸwaren GmbH & Co. KG,Petra Winkler,TiergartenstraÃŸe 5,Berlin,10785,Germany,(010) 9984510
1,12,Plutzer LebensmittelgroÃŸmÃ¤rkte AG,Martin Bein,Bogenallee 51,Frankfurt,60439,Germany,(069) 992755
2,13,Nord-Ost-Fisch Handelsgesellschaft mbH,Sven Petersen,Frahmredder 112a,Cuxhaven,27478,Germany,(04721) 8713

In [22]:
# Display dataframe
print("\nDataFrame for OR operator:")
df_or.head()

DataFrame for OR operator:

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,2,New Orleans Cajun Delights,Shelley Burke,P.O. Box 78934,New Orleans,70117,USA,(100) 555-4822
1,3,Grandma Kelly's Homestead,Regina Murphy,707 Oxford Rd.,Ann Arbor,48104,USA,(313) 555-5735
2,11,Heli SÃ¼ÃŸwaren GmbH & Co. KG,Petra Winkler,TiergartenstraÃŸe 5,Berlin,10785,Germany,(010) 9984510
3,12,Plutzer LebensmittelgroÃŸmÃ¤rkte AG,Martin Bein,Bogenallee 51,Frankfurt,60439,Germany,(069) 992755
4,13,Nord-Ost-Fisch Handelsgesellschaft mbH,Sven Petersen,Frahmredder 112a,Cuxhaven,27478,Germany,(04721) 8713

In [23]:
# Display dataframe
print("\nDataFrame for NOT operator:")
df_not.head()

DataFrame for NOT operator:

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,1,Exotic Liquid,Charlotte Cooper,49 Gilbert St.,Londona,EC1 4SD,UK,(171) 555-2222
1,2,New Orleans Cajun Delights,Shelley Burke,P.O. Box 78934,New Orleans,70117,USA,(100) 555-4822
2,3,Grandma Kelly's Homestead,Regina Murphy,707 Oxford Rd.,Ann Arbor,48104,USA,(313) 555-5735
3,4,Tokyo Traders,Yoshi Nagase,9-8 Sekimai Musashino-shi,Tokyo,100,Japan,(03) 3555-5011
4,5,Cooperativa de Quesos 'Las Cabras',Antonio del Valle Saavedra,Calle del Rosal 4,Oviedo,33007,Spain,(98) 598 76 54

In [24]:
# Display dataframe
print("\nDataFrame for = operator:")
df_equal.head()

DataFrame for = operator:

Empty DataFrame
Columns: [SupplierID, SupplierName, ContactName, Address, City, PostalCode, Country, Phone]
Index: []

In [25]:
# Display dataframe
print("\nDataFrame for < operator:")
df_less_than.head()

DataFrame for < operator:

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,1,Exotic Liquid,Charlotte Cooper,49 Gilbert St.,Londona,EC1 4SD,UK,(171) 555-2222
1,2,New Orleans Cajun Delights,Shelley Burke,P.O. Box 78934,New Orleans,70117,USA,(100) 555-4822
2,3,Grandma Kelly's Homestead,Regina Murphy,707 Oxford Rd.,Ann Arbor,48104,USA,(313) 555-5735
3,4,Tokyo Traders,Yoshi Nagase,9-8 Sekimai Musashino-shi,Tokyo,100,Japan,(03) 3555-5011
4,5,Cooperativa de Quesos 'Las Cabras',Antonio del Valle Saavedra,Calle del Rosal 4,Oviedo,33007,Spain,(98) 598 76 54

In [26]:
# Display dataframe
print("\nDataFrame for > operator:")
df_greater_than.head()

DataFrame for > operator:

Empty DataFrame
Columns: [SupplierID, SupplierName, ContactName, Address, City, PostalCode, Country, Phone]
Index: []

In [27]:
# Display dataframe
print("\nDataFrame for <= operator:")
df_less_than_or_equal.head()

DataFrame for <= operator:

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,1,Exotic Liquid,Charlotte Cooper,49 Gilbert St.,Londona,EC1 4SD,UK,(171) 555-2222
1,2,New Orleans Cajun Delights,Shelley Burke,P.O. Box 78934,New Orleans,70117,USA,(100) 555-4822
2,3,Grandma Kelly's Homestead,Regina Murphy,707 Oxford Rd.,Ann Arbor,48104,USA,(313) 555-5735
3,4,Tokyo Traders,Yoshi Nagase,9-8 Sekimai Musashino-shi,Tokyo,100,Japan,(03) 3555-5011
4,5,Cooperativa de Quesos 'Las Cabras',Antonio del Valle Saavedra,Calle del Rosal 4,Oviedo,33007,Spain,(98) 598 76 54

In [28]:
# Display dataframe
print("\nDataFrame for >= operator:")
df_greater_than_or_equal.head()

DataFrame for >= operator:

Empty DataFrame
Columns: [SupplierID, SupplierName, ContactName, Address, City, PostalCode, Country, Phone]
Index: []

In [29]:
# Display dataframe
print("\nDataFrame for <> (not equal) operator:")
df_not_equal.head()

DataFrame for <> (not equal) operator:

,SupplierID,SupplierName,ContactName,Address,City,PostalCode,Country,Phone
0,1,Exotic Liquid,Charlotte Cooper,49 Gilbert St.,Londona,EC1 4SD,UK,(171) 555-2222
1,4,Tokyo Traders,Yoshi Nagase,9-8 Sekimai Musashino-shi,Tokyo,100,Japan,(03) 3555-5011
2,5,Cooperativa de Quesos 'Las Cabras',Antonio del Valle Saavedra,Calle del Rosal 4,Oviedo,33007,Spain,(98) 598 76 54
3,6,Mayumi's,Mayumi Ohno,92 Setsuko Chuo-ku,Osaka,545,Japan,(06) 431-7877
4,7,"Pavlova, Ltd.",Ian Devling,74 Rose St. Moonie Ponds,Melbourne,3058,Australia,(03) 444-2343

Common functions in `SQLite` are given in the following table:

| Function | Description                                          |
|----------|------------------------------------------------------|
| `SUM()`  | Calculates the sum of values in a column.           |
| `AVG()`  | Calculates the average of values in a column.       |
| `MIN()`  | Finds the minimum value in a column.                |
| `MAX()`  | Finds the maximum value in a column.                |
| `COUNT()`| Counts the number of rows in a result set.          |

In [30]:
# Connect to the Northwind database
conn = sqlite3.connect('Northwind.db')

# Example of SUM()
df_sum = pd.read_sql_query("""
    SELECT SUM(Price) AS TotalPrice FROM Products;
""", conn)

# Example of AVG()
df_avg = pd.read_sql_query("""
    SELECT AVG(Price) AS AveragePrice FROM Products;
""", conn)

# Example of MIN()
df_min = pd.read_sql_query("""
    SELECT MIN(Price) AS MinimumPrice FROM Products;
""", conn)

# Example of MAX()
df_max = pd.read_sql_query("""
    SELECT MAX(Price) AS MaximumPrice FROM Products;
""", conn)

# Example of COUNT()
df_count = pd.read_sql_query("""
    SELECT COUNT(*) AS ProductsCount FROM Products;
""", conn)

# Close the connection
conn.close()

In [31]:
# Display dataframe
print("Total Freight:")
df_sum.head()

Total Freight:

   TotalPrice
0     2222.71

In [32]:
# Display dataframe
print("\nAverage Freight:")
df_avg.head()

Average Freight:

   AveragePrice
0     28.866364

In [33]:
# Display dataframe
print("\nMinimum Freight:")
df_min.head()

Minimum Freight:

   MinimumPrice
0           2.5

In [34]:
# Display dataframe
print("\nMaximum Freight:")
df_max.head()

Maximum Freight:

   MaximumPrice
0         263.5

In [35]:
# Display dataframe
print("\nOrder Count:")
df_count.head()

Order Count:

   ProductsCount
0             77

Other common functions in `SQLite` are given in the following table

| Function | Description                                          |
|----------|------------------------------------------------------|
| `UNION`  | Combines the result sets of two or more SELECT statements without including duplicate rows. |
| `CONCAT` | Concatenates two or more strings.                    |
| `TRIM`   | Removes leading and trailing spaces from a string.   |
| `LTRIM`  | Removes leading spaces from a string.                |
| `RTRIM`  | Removes trailing spaces from a string.               |
| `CAST`   | Converts a value from one data type to another.      |

In [36]:
# Connect to the Northwind database
conn = sqlite3.connect('Northwind.db')

# Example of UNION
df_union = pd.read_sql_query("""
    SELECT ProductName FROM Products WHERE CategoryID = 1
    UNION
    SELECT ProductName FROM Products WHERE CategoryID = 2;
""", conn)

# Example of CONCAT
df_concat = pd.read_sql_query("""
    SELECT ProductName || ' - ' || Unit AS ProductInfo FROM Products;
""", conn)

# Example of TRIM
df_trim = pd.read_sql_query("""
    SELECT TRIM('   Hello World   ') AS TrimmedString;
""", conn)

# Example of LTRIM
df_ltrim = pd.read_sql_query("""
    SELECT LTRIM('   Hello World   ') AS LeftTrimmedString;
""", conn)

# Example of RTRIM
df_rtrim = pd.read_sql_query("""
    SELECT RTRIM('   Hello World   ') AS RightTrimmedString;
""", conn)

# Example of CAST
df_cast = pd.read_sql_query("""
    SELECT CAST(Price AS INTEGER) AS PriceInteger FROM Products;
""", conn)

# Close the connection
conn.close()

In [37]:
# Display dataframe
print("Union of Product Names from Categories 1 and 2:")
df_union.head()

Union of Product Names from Categories 1 and 2:

                    ProductName
0                 Aniseed Syrup
1                         Chais
2                         Chang
3              Chartreuse verte
4  Chef Anton's Cajun Seasoning

In [38]:
# Display dataframe
print("\nConcatenated Product Information:")
df_concat.head()

Concatenated Product Information:

                                     ProductInfo
0                     Chais - 10 boxes x 20 bags
1                     Chang - 24 - 12 oz bottles
2            Aniseed Syrup - 12 - 550 ml bottles
3  Chef Anton's Cajun Seasoning - 48 - 6 oz jars
4              Chef Anton's Gumbo Mix - 36 boxes

In [39]:
# Display dataframe
print("\nTrimmed String:")
df_trim.head()

Trimmed String:

  TrimmedString
0   Hello World

In [40]:
# Display dataframe
print("\nLeft Trimmed String:")
df_ltrim.head()

Left Trimmed String:

  LeftTrimmedString
0    Hello World

In [41]:
# Display dataframe
print("\nRight Trimmed String:")
df_rtrim.head()

Right Trimmed String:

  RightTrimmedString
0        Hello World

In [42]:
# Display dataframe
print("\nCasted Price to Integer:")
df_cast.head()

Casted Price to Integer:

   PriceInteger
0            18
1            19
2            10
3            22
4            21

`SQLite` Join Commands and Functions

| Command      | Description                                                  |
|--------------|--------------------------------------------------------------|
| `INNER JOIN` | Retrieves records that have matching values in both tables.  |
| `OUTER JOIN` | Retrieves all records when there is a match in either table. |
| `LEFT JOIN`  | Retrieves all records from the left table and matching records from the right table. |
| `RIGHT JOIN` | Retrieves all records from the right table and matching records from the left table. |
| `FULL JOIN`  | Retrieves all records when there is a match in either table, similar to `OUTER JOIN`. |
| `SELF JOIN`  | Joins a table to itself.                                     |
| `CASE`       | Used to create conditional expressions.                      |

In [43]:
# Connect to the Northwind database
conn = sqlite3.connect('Northwind.db')

# Example of INNER JOIN
df_inner_join = pd.read_sql_query("""
    SELECT Orders.OrderID, Customers.CustomerName
    FROM Orders
    INNER JOIN Customers ON Orders.CustomerID = Customers.CustomerID;
""", conn)

# Example of OUTER JOIN
df_outer_join = pd.read_sql_query("""
    SELECT Orders.OrderID, Customers.CustomerName
    FROM Orders
    LEFT JOIN Customers ON Orders.CustomerID = Customers.CustomerID;
""", conn)

# Example of LEFT JOIN
df_left_join = pd.read_sql_query("""
    SELECT Orders.OrderID, Customers.CustomerName
    FROM Orders
    LEFT JOIN Customers ON Orders.CustomerID = Customers.CustomerID;
""", conn)

# Example of RIGHT JOIN
df_right_join = pd.read_sql_query("""
    SELECT Orders.OrderID, Customers.CustomerName
    FROM Orders
    RIGHT JOIN Customers ON Orders.CustomerID = Customers.CustomerID;
""", conn)

# Example of FULL JOIN
df_full_join = pd.read_sql_query("""
    SELECT Orders.OrderID, Customers.CustomerName
    FROM Orders
    FULL JOIN Customers ON Orders.CustomerID = Customers.CustomerID;
""", conn)

# Example of SELF JOIN
df_self_join = pd.read_sql_query("""
    SELECT a.ProductName, b.ProductName AS RelatedProduct
    FROM Products a
    INNER JOIN Products b ON a.SupplierID = b.SupplierID
    WHERE a.ProductName <> b.ProductName;
""", conn)

# Close the connection
conn.close()

In [44]:
# Display dataframe
print("DataFrame for INNER JOIN:")
df_inner_join.head()

DataFrame for INNER JOIN:

   OrderID              CustomerName
0    10248               Wilman Kala
1    10249  TradiÃ§Ã£o Hipermercados
2    10250             Hanari Carnes
3    10251      Victuailles en stock
4    10252        SuprÃªmes dÃ©lices

In [45]:
# Display dataframe
print("\nDataFrame for OUTER JOIN:")
df_outer_join.head()

DataFrame for OUTER JOIN:

   OrderID              CustomerName
0    10248               Wilman Kala
1    10249  TradiÃ§Ã£o Hipermercados
2    10250             Hanari Carnes
3    10251      Victuailles en stock
4    10252        SuprÃªmes dÃ©lices

In [46]:
# Display dataframe
print("\nDataFrame for LEFT JOIN:")
df_left_join.head()

DataFrame for LEFT JOIN:

   OrderID              CustomerName
0    10248               Wilman Kala
1    10249  TradiÃ§Ã£o Hipermercados
2    10250             Hanari Carnes
3    10251      Victuailles en stock
4    10252        SuprÃªmes dÃ©lices

In [47]:
# Display dataframe
print("\nDataFrame for RIGHT JOIN:")
df_right_join.head()

DataFrame for RIGHT JOIN:

   OrderID              CustomerName
0  10248.0               Wilman Kala
1  10249.0  TradiÃ§Ã£o Hipermercados
2  10250.0             Hanari Carnes
3  10251.0      Victuailles en stock
4  10252.0        SuprÃªmes dÃ©lices

In [48]:
# Display dataframe
print("\nDataFrame for FULL JOIN:")
df_full_join.head()

DataFrame for FULL JOIN:

   OrderID              CustomerName
0  10248.0               Wilman Kala
1  10249.0  TradiÃ§Ã£o Hipermercados
2  10250.0             Hanari Carnes
3  10251.0      Victuailles en stock
4  10252.0        SuprÃªmes dÃ©lices

In [49]:
# Display dataframe
print("\nDataFrame for SELF JOIN:")
df_self_join.head()

DataFrame for SELF JOIN:

     ProductName RelatedProduct
0          Chais  Aniseed Syrup
1          Chais          Chang
2          Chang  Aniseed Syrup
3          Chang          Chais
4  Aniseed Syrup          Chais

### 14.8.6. Temporary Tables and Views in `SQL`

- Temporary tables in SQLite are tables that exist for the duration of a session or a transaction. They are useful for storing intermediate results or temporary data that is needed within a specific scope but does not need to persist beyond that scope. Temporary tables are automatically dropped when the session ends or the transaction completes.

- Views in SQLite are virtual tables that represent the result set of a SELECT statement. They provide a way to simplify complex queries and encapsulate logic by storing them as named objects in the database. Views can be queried like regular tables, but they do not store any data themselves. Instead, they dynamically generate the result set based on the underlying query.

In [50]:
# Connect to the Northwind database
conn = sqlite3.connect('Northwind.db')

# Create a temporary table with the top 5 orders
conn.execute("""
CREATE TEMPORARY TABLE temp_orders AS
SELECT * FROM Orders
ORDER BY OrderDate DESC
LIMIT 5;
""")

# Query the temporary table
df_temp_orders = pd.read_sql_query("""
SELECT * FROM temp_orders;
""", conn)

# Close the connection
conn.close()

# Display the temporary table
print("Temporary Table (Top 5 Orders):")
df_temp_orders

Temporary Table (Top 5 Orders):

   OrderID  CustomerID  EmployeeID   OrderDate  ShipperID
0    10443          66           8  1997-02-12          1
1    10442          20           3  1997-02-11          2
2    10440          71           4  1997-02-10          2
3    10441          55           3  1997-02-10          2
4    10439          51           6  1997-02-07          3

In [51]:
# Connect to the Northwind database
conn = sqlite3.connect('northwind.db')

# Create a cursor
cursor = conn.cursor()

# Drop the view if it exists
cursor.execute("DROP VIEW IF EXISTS expensive_products_view")

# Commit the changes
conn.commit()

# Close the cursor
cursor.close()

# Create a new cursor
cursor = conn.cursor()

# Create the view
cursor.execute("""
CREATE VIEW expensive_products_view AS
SELECT *
FROM Products
WHERE Price > 50
""")

# Commit the changes
conn.commit()

# Query the view
df_expensive_products = pd.read_sql_query("""
SELECT * FROM expensive_products_view
""", conn)

# Close the connection
conn.close()

# Display the view
print("\nView (Expensive Products):")
df_expensive_products

View (Expensive Products):

,ProductID,ProductName,SupplierID,CategoryID,Unit,Price
0,9,Mishi Kobe Niku,4,6,18 - 500 g pkgs.,97.00
1,18,Carnarvon Tigers,7,8,16 kg pkg.,62.50
2,20,Sir Rodney's Marmalade,8,3,30 gift boxes,81.00
3,29,ThÃ¼ringer Rostbratwurst,12,6,50 bags x 30 sausgs.,123.79
4,38,CÃ´te de Blaye,18,1,12 - 75 cl bottles,263.50
5,51,Manjimup Dried Apples,24,7,50 - 300 g pkgs.,53.00
6,59,Raclette Courdavault,28,4,5 kg pkg.,55.00

### 14.8.7. Databases from `.csv` files

It is possible to create databases from `.csv` files

In [52]:
import os
import csv

# Example data for CSV files
data1 = [
    {'ID': 1, 'Name': 'John', 'Age': 30},
    {'ID': 2, 'Name': 'Alice', 'Age': 25},
    {'ID': 3, 'Name': 'Bob', 'Age': 35}
]

data2 = [
    {'ProductID': 101, 'ProductName': 'Phone', 'Price': 500},
    {'ProductID': 102, 'ProductName': 'Laptop', 'Price': 1000},
    {'ProductID': 103, 'ProductName': 'Tablet', 'Price': 300}
]

# Write data to CSV files
with open('data1.csv', 'w', newline='') as csvfile:
    fieldnames = ['ID', 'Name', 'Age']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data1)

with open('data2.csv', 'w', newline='') as csvfile:
    fieldnames = ['ProductID', 'ProductName', 'Price']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data2)

# Connect to SQLite database
conn = sqlite3.connect('example_csv.db')
conn.execute("PRAGMA foreign_keys = ON")
conn.execute("BEGIN")

cursor = conn.cursor()

# Check if tables exist, drop them if they do
cursor.execute('''DROP TABLE IF EXISTS users''')
cursor.execute('''DROP TABLE IF EXISTS products''')

# Commit changes and close connection
conn.commit()
conn.close()

# Connect to SQLite database again
conn = sqlite3.connect('example_csv.db')
cursor = conn.cursor()

# Create tables from CSV files
cursor.execute('''CREATE TABLE IF NOT EXISTS users
                  (ID INTEGER PRIMARY KEY, Name TEXT, Age INTEGER)''')

cursor.execute('''CREATE TABLE IF NOT EXISTS products
                  (ProductID INTEGER PRIMARY KEY, ProductName TEXT, Price INTEGER)''')

# Import data from CSV files
with open('data1.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        cursor.execute('INSERT INTO users (ID, Name, Age) VALUES (?, ?, ?)', (row['ID'], row['Name'], row['Age']))

with open('data2.csv', 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        cursor.execute('INSERT INTO products (ProductID, ProductName, Price) VALUES (?, ?, ?)', 
                       (row['ProductID'], row['ProductName'], row['Price']))

# Commit changes and close connection
conn.commit()
conn.close()

In [53]:
# Connect to the SQLite database
conn = sqlite3.connect('example_csv.db')
cursor = conn.cursor()

# Execute a query to fetch data from the users table
cursor.execute("SELECT * FROM users")
users_data = cursor.fetchall()

# Execute a query to fetch data from the products table
cursor.execute("SELECT * FROM products")
products_data = cursor.fetchall()

# Print the retrieved data
print("Users Data:")
for row in users_data:
    print(row)

print("\nProducts Data:")
for row in products_data:
    print(row)

# Close the connection
conn.close()

Users Data:
(1, 'John', 30)
(2, 'Alice', 25)
(3, 'Bob', 35)

Products Data:
(101, 'Phone', 500)
(102, 'Laptop', 1000)
(103, 'Tablet', 300)

### 14.8.8. Connect and upload data to an AWS database

In [54]:
# Install redshift_connector
# !pip install redshift_connector

# Modules to connect to the database
# import redshift_connector
# from sqlalchemy import create_engine
# To upload .csv files to S3.
# import sagemaker
# import boto3
# from io import StringIO

In [55]:
# Define the Redshift connection parameters
# redshift_host = 'your_redshift_host'
# redshift_database = 'your_redshift_database'
# redshift_port = your_port_number

# Connect to the Redshift cluster
# conn = redshift_connector.connect(
#     host=redshift_host,
#     database=redshift_database,
#     port=redshift_port,
#     user='your_username',
#     password='your_password'
# )

# Create a cursor object
# cur = conn.cursor()

In [56]:
# File name
# file_name = 'file.csv'

# Save DataFrame as CSV
# input_data.to_csv(file_name, index=False)

# Upload the CSV file to Amazon S3
# bucket_name = 'your_s3_bucket_name'  # Replace with your bucket name
# s3_path = f'your/s3/path/{file_name}'

# Get the default SageMaker execution role
# role = sagemaker.get_execution_role()

# Create S3 client without specifying credentials
# s3_client = boto3.client('s3')

# Upload the file to S3 bucket
# s3_client.upload_file(file_name, bucket_name, s3_path)

# print(f'File {file_name} uploaded to S3 at path {s3_path}')

In [57]:
# Redshift connection configuration
# redshift_config = {
#    'host': 'your_redshift_host',
#    'database': 'your_redshift_database',
#    'port': your_number_port,
#    'user': 'your_redshift_username',
#    'password': 'your_redshift_password'
# }

# Establish connection to Redshift
# conn = redshift_connector.connect(**redshift_config)

# Create cursor object
# cur = conn.cursor()

# Define S3 file path (replace 'your_bucket_name' and 'your_path' with your S3 bucket and path)
#s3_bucket = 'your_bucket_name'
# s3_path = 'your_path/file_name'

# Table name in Redshift
# table_name = "your_redshift_table_name"

# Your COPY query (replace 'your_redshift_role_arn' with your IAM role ARN)
# copy_query = """
#    COPY schema_name.{table_name}
#    FROM 's3://{s3_bucket}/{s3_path}'
#    IAM_ROLE 'your_redshift_role_arn'
#    CSV
#    IGNOREHEADER 1
#    DELIMITER ',';
# """.format(table_name=table_name, s3_bucket=s3_bucket, s3_path=s3_path)

# Execute COPY command
# cur.execute(copy_query)

# Commit to apply changes
# conn.commit()

# Close cursor and connection
# cur.close()
# conn.close()

# print(f'Data load from S3 to Redshift completed for table {table_name}')